import { useEffect, useState } from "react";
import { ArrowRight, FlaskConical } from "lucide-react";
import { Link } from "react-router-dom";

const SECTIONS = ["Research Projects", "GIS Projects", "GeoAI Projects", "Remote Sensing Projects", "Urban Planning Projects", "Student Projects", "Community Projects"];

export default function Research() {
  const [items, setItems] = useState([]);
  const [form, setForm] = useState({ title: "", description: "", category: "", projectUrl: "" });
  const [state, setState] = useState("");
  useEffect(() => { setItems(JSON.parse(localStorage.getItem("geodata-hub-research") || "[]")); }, []);
  function submit(event) { event.preventDefault(); const next = [...items, { ...form, id: Date.now(), status: "PENDING_REVIEW" }]; localStorage.setItem("geodata-hub-research", JSON.stringify(next)); setItems(next); setForm({ title: "", description: "", category: "", projectUrl: "" }); setState("Saved locally as PENDING_REVIEW"); }
  return <div className="mx-auto max-w-6xl px-4 py-12 sm:px-6"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-brand-700">Knowledge in action</p><h1 className="mt-2 text-3xl font-black text-gray-900">Research & Projects</h1><p className="mt-2 text-base leading-relaxed text-gray-600">Explore project themes and save a project submission locally for later review.</p></div><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{SECTIONS.map((section) => <div key={section} className="card p-4"><FlaskConical className="h-5 w-5 text-brand-600" /><h2 className="mt-3 text-sm font-bold text-gray-900">{section}</h2></div>)}</div><section className="mt-10"><div className="flex items-end justify-between"><div><h2 className="text-xl font-bold text-gray-900">Saved projects</h2><p className="mt-1 text-sm text-gray-600">No server or account is required for this frontend-only draft.</p></div><Link to="/contact" className="inline-flex items-center gap-1 text-sm font-semibold text-brand-700">Collaborate <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-4 grid gap-4 md:grid-cols-2">{items.map((item) => <article key={item.id} className="card p-5"><span className="badge bg-amber-50 text-amber-700">{item.status}</span><h3 className="mt-2 font-bold text-gray-900">{item.title}</h3><p className="mt-2 text-sm leading-relaxed text-gray-600">{item.description}</p></article>)}{!items.length && <div className="card col-span-full p-10 text-center text-sm text-gray-500">No project drafts yet.</div>}</div></section><section className="mt-10 card p-6"><h2 className="text-xl font-bold text-gray-900">Submit a project draft</h2><form onSubmit={submit} className="mt-5 grid gap-4 sm:grid-cols-2"><input className="input" required placeholder="Project title" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /><input className="input" placeholder="Category" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} /><textarea className="input min-h-32 sm:col-span-2" required placeholder="Description" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /><input className="input sm:col-span-2" type="url" placeholder="Project URL" value={form.projectUrl} onChange={(e) => setForm({ ...form, projectUrl: e.target.value })} /><button className="btn-primary sm:col-span-2">Save project draft</button></form>{state && <p className="mt-3 text-sm text-brand-700">{state}</p>}</section></div>;
}
