import { ArrowRight, BookOpen, PackageOpen } from "lucide-react";
import { Link } from "react-router-dom";
import AcademySocialLinks from "../components/AcademySocialLinks.jsx";
import AcademyIcon from "../components/academy/AcademyIcon.jsx";
import { GEORESOURCES } from "../data/resources.js";

export default function Resources() {
  return (
    <div>
      <section className="bg-brand-950 text-white"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:py-16"><div className="max-w-4xl"><span className="badge bg-white/10 text-brand-200 ring-1 ring-white/20"><PackageOpen className="h-3.5 w-3.5" aria-hidden="true" /> GeoBrains Resources</span><h1 className="mt-5 text-4xl font-black tracking-tight sm:text-5xl">Tools, data and knowledge for geospatial work.</h1><p className="mt-4 max-w-3xl text-lg leading-relaxed text-gray-300">A curated bridge across the GIS &amp; Remote Sensing Hub catalogue, GeoBrains Academy learning paths and official geospatial resources.</p><div className="mt-7 flex flex-wrap gap-3"><Link to="/data" className="btn-primary bg-brand-500 hover:bg-brand-400">Browse datasets <ArrowRight className="h-4 w-4" aria-hidden="true" /></Link><Link to="/software" className="inline-flex items-center gap-2 rounded-lg border border-white/20 px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-white/10">Explore software</Link><Link to="/training" className="inline-flex items-center gap-2 rounded-lg border border-white/20 px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-white/10"><BookOpen className="h-4 w-4" aria-hidden="true" /> Learn with Academy</Link></div><AcademySocialLinks dark follow className="mt-4" /></div></div></section>
      <main className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:py-16"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-brand-700">A practical starting point</p><h2 className="mt-2 text-2xl font-black text-gray-900 sm:text-3xl">Find the next resource for your workflow</h2><p className="mt-3 text-sm leading-relaxed text-gray-600">Use official source links where they exist, and use the Hub catalogue and Academy pathways to move from discovery to practical application.</p></div><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{GEORESOURCES.map((resource) => <article key={resource.id} className="card flex flex-col p-5 transition hover:-translate-y-0.5 hover:border-brand-400 hover:shadow-md"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-brand-50 text-brand-700"><AcademyIcon name={resource.icon} className="h-5 w-5" /></span><h3 className="mt-4 text-lg font-bold text-gray-900">{resource.title}</h3><p className="mt-1.5 flex-1 text-sm leading-relaxed text-gray-600">{resource.description}</p>{resource.href ? <a href={resource.href} target="_blank" rel="noopener noreferrer" className="btn-secondary mt-5 justify-center">{resource.label} <ArrowRight className="h-4 w-4" aria-hidden="true" /></a> : <Link to={resource.to} className="btn-secondary mt-5 justify-center">{resource.label} <ArrowRight className="h-4 w-4" aria-hidden="true" /></Link>}</article>)}</div></main>
    </div>
  );
}
