import {
  BarChart3,
  BookOpen,
  Bot,
  Boxes,
  Brain,
  Briefcase,
  Building2,
  Cloud,
  Code2,
  Database,
  Globe2,
  ImageIcon,
  Layers3,
  Map,
  MapPinned,
  Network,
  Orbit,
  PanelTop,
  Plane,
  RadioTower,
  Rocket,
  Satellite,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Waves,
  Workflow,
  Wrench,
} from "lucide-react";

const ICONS = {
  map: Map,
  layers: Layers3,
  satellite: Satellite,
  bot: Bot,
  brain: Brain,
  chart: BarChart3,
  globe: Globe2,
  cloud: Cloud,
  building: Building2,
  city: Building2,
  drone: Plane,
  rocket: Rocket,
  briefcase: Briefcase,
  code: Code2,
  tool: Wrench,
  water: Waves,
  image: ImageIcon,
  location: MapPinned,
  mobile: Smartphone,
  security: ShieldCheck,
  research: BookOpen,
  book: BookOpen,
  dashboard: PanelTop,
  agent: Bot,
  automation: Workflow,
  "3d": Boxes,
  realtime: RadioTower,
  iot: Network,
  spatial: Orbit,
  database: Database,
  sparkles: Sparkles,
};

export default function AcademyIcon({ name = "map", className = "h-5 w-5", ...props }) {
  const Icon = ICONS[name] || Map;
  return <Icon className={className} aria-hidden="true" {...props} />;
}
